export default {
  food: [
    "🐄 milk",
    "🥑 avocado",
    "🍞 bread",
    "🥓 bacon",
    "🥦 broccoli",
    "🍳 eggs",
    "🥗 salad",
    "🍝 spaghetti",
  ],
  personal: [
    "🎓 study js",
    "🇩🇪 learn german",
    "🎲 game with friends",
    "🦷 dentist appoinment",
    "👩‍⚕️ dr. appoinment",
    "💵 pay rent",
    "💵 do taxes",
    "🎊 plan bday",
  ],
  exercise: [
    "🧗‍♂️ climb",
    "🏄 surf",
    "🏊 swim",
    "🛶 canoe",
    "⚽ soccer",
    "👟 running",
    "🧘‍♀️ yoga",
    "🚵‍♀️ cycle",
  ],
  work: [
    "🔍 stackOverflow",
    "📒 ledger",
    "📈 chart",
    "🗄️ file docs",
    "👔 shirt",
    "🐍 python update",
    "💻 laptop",
    "🛠️ build version",
  ],
  general: [
    "🎁 gift",
    "🎧 headphone",
    "🎮 video games",
    "🎬 movies",
    "🚅 train",
    "⛺ tent",
    "✈️ airplane",
    "👨‍🎤 festival",
  ],
};
